version: '3.9'

services:
  mongo:
    image: mongo:5.0
    container_name: tarea1-sd-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:latest
    container_name: tarea1-sd-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru"]
    restart: always

  scraper:
    build:
      context: ./scraper
    container_name: tarea1-sd-scraper
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - DB_NAME=waze_data
    depends_on:
      - mongo
    volumes:
      - ./scraper:/app
    command: python scraper.py
    stdin_open: true
    tty: true

  query:
    build:
      context: ./scraper
    container_name: tarea1-sd-query
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_NAME=waze_data
    depends_on:
      - mongo
      - redis
    volumes:
      - ./scraper:/app
    command: python cache_query.py
    stdin_open: true
    tty: true

  simulate:
    build:
      context: ./scraper
    container_name: tarea1-sd-simulate
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./scraper:/app
    command: python simulate_cache_stress.py

  api:
    build:
      context: ./scraper
    container_name: tarea1-sd-api
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_NAME=waze_data
    depends_on:
      - mongo
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./scraper:/app
    command: python server.py
    restart: always

volumes:
  mongo_data:
