version: '3.9'

services:
  mongo:
    image: mongo:5.0
    container_name: tarea1-sd-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./data/export:/export     # Montaje para exportar datos de Mongo
    restart: always

  redis:
    image: redis:latest
    container_name: tarea1-sd-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru"]
    restart: always

  scraper:
    build:
      context: ./scraper
    container_name: tarea1-sd-scraper
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - DB_NAME=waze_data
    depends_on:
      - mongo
    volumes:
      - ./scraper:/app
      - ./data/export:/export    # Compartido con Mongo
    command: python scraper.py
    stdin_open: true
    tty: true

  query:
    build:
      context: ./scraper
    container_name: tarea1-sd-query
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_NAME=waze_data
    depends_on:
      - mongo
      - redis
    volumes:
      - ./scraper:/app
    command: python cache_query.py
    stdin_open: true
    tty: true

  simulate:
    build:
      context: ./scraper
    container_name: tarea1-sd-simulate
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./scraper:/app
    command: python simulate_cache_stress.py

  api:
    build:
      context: ./scraper
    container_name: tarea1-sd-api
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_NAME=waze_data
    depends_on:
      - mongo
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./scraper:/app
    command: python server.py
    restart: always

  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: tarea2-sd-namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "50070:50070"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: tarea2-sd-datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://tarea2-sd-namenode:8020
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoop

  pig:
    image: bde2020/pig
    container_name: tarea2-sd-pig
    depends_on:
      - hadoop-namenode
    networks:
      - hadoop
    volumes:
      - ./scripts:/scripts          # Aquí van tus scripts .pig
      - ./data/export:/input        # Aquí cargas los datos exportados de Mongo
      - ./data/output:/output       # Aquí Pig deja sus resultados
    tty: true
    stdin_open: true

volumes:
  mongo_data:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop:
