services:
  # Base de datos MongoDB sin autenticación
  mongo:
    image: mongo:5.0
    container_name: tarea1-sd-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  # Redis
  redis:
    image: redis:latest
    container_name: tarea1-sd-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru"]
    restart: always

  # Scraper principal
  scraper:
    build:
      context: ./scraper
    container_name: tarea1-sd-scraper
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - DB_NAME=waze_data
    depends_on:
      - mongo
    volumes:
      - ./scraper:/app
      - ./scraper/jsons:/app/jsons
    command: python scraper.py
    stdin_open: true
    tty: true

  # Query service
  query:
    build:
      context: ./scraper
    container_name: tarea1-sd-query
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_NAME=waze_data
    depends_on:
      - mongo
      - redis
    volumes:
      - ./scraper:/app
    command: python cache_query.py
    stdin_open: true
    tty: true

  # Simulation service
  simulate:
    build:
      context: ./scraper
    container_name: tarea1-sd-simulate
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_NAME=waze_data
    depends_on:
      - mongo
      - redis
    volumes:
      - ./scraper:/app
    command: python simulate_cache_stress.py

  # API Server
  api:
    build:
      context: ./scraper
    container_name: tarea1-sd-api
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_NAME=waze_data
    depends_on:
      - mongo
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./scraper:/app
    command: python server.py
    restart: always

  # Análisis de datos unificado (filtrado + procesamiento + visualización)
  analisis_trafico:
    build:
      context: ./analisis-trafico
    container_name: tarea1-sd-analisis-trafico
    volumes:
      - ./analisis-trafico/data:/app/data
      - ./analisis-trafico/results:/app/results
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - MONGODB_DB=waze_data
      - MONGODB_COLECCION_ALERTAS=alertas
      - MONGODB_COLECCION_ATASCOS=atascos
    depends_on:
      - mongo
    # Puedes ejecutar manualmente cuando necesites o comentar la línea siguiente para auto-ejecutar
    # command: ./run.sh

volumes:
  mongo_data: